FROM php:7.2-apache

# Set the php extensions you need for your project
# Note: Debian 10 reached end of support, and its repository has 
#       been archived, the docker image maintainers did not update 
#       the sources.list file, we do it here before apt update.
RUN rm /etc/apt/sources.list && \
    export DISTRIBUTION_NAME=$(grep "VERSION=" /etc/os-release | sed 's/^.*(\(.*\)).*$/\1/') && \
    echo "deb http://archive.debian.org/debian/ ${DISTRIBUTION_NAME} main" >> /etc/apt/sources.list && \
    apt update && \
    apt install -y libfreetype6-dev libjpeg62-turbo-dev libwebp-dev libpng-dev libzip-dev zip && \
    pecl install xdebug-3.1.6 && \
    a2enmod rewrite && \
    docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-webp-dir=/usr/include/ && \
    docker-php-ext-install mysqli pdo pdo_mysql gd exif zip && \
    docker-php-ext-enable xdebug

# To make sur that the bind-mounted files inside the container 
# are owned by www-data, run the container with the www-data 
# user instead of root.
USER www-data:www-data
